### ISSUE TITLE
hope you add registration and google.json

### ISSUE THREAD

**Issue by mynameismhmd** [krupal22/Flutter-Login-Page-Design#1]

**Comment by krupal22** [comment]
@mynameismhmd this is a demonstrate design only so i can add registration for that i need some time. and as i understand you talk about  google.json file so i think you are talking about firebase. but sorry as i mention this is just for demonstrate a Ui design so i can not implement  this functionality here. but may be i can create new project for that in future and my be i create video for my Youtube channel.

**Comment by mynameismhmd** [comment]
ok hope you do it fast
